### ISSUE TITLE
Add Validation for CLI values

### ISSUE THREAD

**Issue by JesseMaitland** [JesseMaitland/superglue#3]
It should not be possible to have a - in the name of a job or module, as then you are not able to import the module into other scripts.

So as an example, I created a job myjob-de-glue-job and in the folder tests  it created a file test_myjob-de-glue-job.py  with the statement import myjob-de-glue-job <== this is not valid statement in Python

The solution to this problem would be to add some simple input validation for the values passed into CLI arguments.

**Comment by jakub-szczepaniak** [comment]
maybe we can allow names with `-` but then convert these into `_` when used as a module name?
